### ISSUE TITLE
Google play services extension 

### ISSUE THREAD

**Issue by badresekkai** [GameMakerStudio2Cracker/GameMakerStudio2Cracks#2]
thank you for providing us with this crack, it worked so well, is it possible to get google play services extension to work with this crack?

**Comment by GameMakerStudio2Cracker** [comment]
Do you mean you can't download the `Google Play Services` Add-on from the IDE?
That's because the account in the IDE isn't actually a real account so it can't download items from the Marketplace.
What you should do is download the extension from [his Marketplace page](https://marketplace.yoyogames.com/assets/2008/google-play-services) with a 30 day trial account.

**Comment by badresekkai** [comment]
it seems that we don't even need the account to download the extension! 
anyone can get access to the download link bellow
just import it to game maker by dragging it to the IDE window
 https://l.facebook.com/l.php?u=https%3A%2F%2Fmarketplacecdn.yoyogames.com%2Fassets%2F2008%2F1590228769_yoyogames.googleplayservicesextension.yymp%3F1590228784%26fbclid%3DIwAR0hf25sUij6Wx4o3OZteXuGhduux3qHSpSjdXwW3rrBri7Yg3BF4CnMnv4&h=AT34r5cXP3ncMS8SemYbTqYRPW68nv8u1rth4MDYONgKkYFYmUwCSmaFDkcHxY1A4FdUJ9W_57tfXoukZEHLoeFtyuK6vx0vDolPgY95kp_nZybdavHKzJIXXVltuxbWa2tMyA

**Comment by GameMakerStudio2Cracker** [comment]
So apparently, after you add an item to your account and ask YoYoGames for a download link, it gives a download link that everybody can use(don't know about paid items).
And for the record, this is one without redirection:
https://marketplacecdn.yoyogames.com/assets/2008/1590228769_yoyogames.googleplayservicesextension.yymp
